//go:build arm64 && blake3asm

package blake3

// mix4 runs BLAKE3's 7 mixing rounds across 4 lanes (4 chunks in parallel, one
// per uint32 lane), in place. Generated by go-asmgen (see mix4_neon_gen.go),
// implemented in mix4_arm64.s. Pure NEON Add/Xor/rotate — works on stable Go,
// no GOEXPERIMENT. Must match the scalar round() applied 7 times, per lane.
func mix4(state *[16][4]uint32, m *[16][4]uint32)
