//go:build amd64 && !goexperiment.simd

package blake3

// mix4 runs BLAKE3's 7 mixing rounds across 4 lanes, in place. Generated by
// go-asmgen (mix4_sse_gen.go), implemented in mix4_amd64.s (SSE2). Companion to
// the arm64 NEON kernel; both work on stable Go with no GOEXPERIMENT.
func mix4(state *[16][4]uint32, m *[16][4]uint32)
